version: "3"

services:
  front:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: web
    # restart: always
    ports:
      - 3000:3000
    volumes:
      - ./frontend/src/:/front/ilonkacloud
    command: >
      /bin/sh -c "npm i &&
                  npm run dev"
  back:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: back
    ports:
      - 8000:8000
    volumes:
      - ./backend/:/app