version: "3"

services:
  front:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: web
    # restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src/:/front/ilonkacloud
    command: >
      /bin/sh -c "npm i &&
                  npm run dev"
  back:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: back
    expose:
      - 8000
    volumes:
      - ./backend/:/app
  db:
    image: postgres:15.3-bullseye
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    expose:
      - 54321
    volumes: 
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local